version: "3.8"
services:
  hurlenko-file:
    image: hurlenko/filebrowser
    user: "1000:1000"
    container_name: filebrowser
    ports:
      - "8010:8080"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - "/opt:/data"
      - "/opt/data-docker/volumes/filebrowser/config/settings.json:/config/settings.json"
      - "/opt/data-docker/volumes/filebrowser/config:/config"
      - "/home:/data/home/"

