version: "3.8"
services:
  hurlenko-file:
    image: hurlenko/filebrowser
    user: "1000:1000"
    container_name: filebrowser
    ports:
      - "8010:8080"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - "/opt:/data"
      - "/opt/data-docker/volumes/filebrowser/config/settings.json:/config/settings.json"
      - "/opt/data-docker/volumes/filebrowser/config:/config"
      - "/home:/data/home/"
      - "nfs01_mydata:/data/nfs01/my_data"

volumes:
  nfs01_mydata:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.41,nolock,soft,rw,nfsvers=4"
      device: ":/srv/nfs04T01/my_data"


