version: '3'

services:
  joplindb:
    image: postgres:15
    volumes:
      - /opt/data-docker/volumes/joplindb/postgresql:/var/lib/postgresql/data
    ports:
      - ":5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DBNAME}
  app:
    image: joplin/server:latest
    depends_on:
      - joplindb
    ports:
      - ":22300"
    restart: unless-stopped
    environment:
      - APP_PORT=${PORT}
      - APP_BASE_URL=https://websiteurl.com
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - MAILER_ENABLED=1
      - MAILER_HOST=smtp.mailgun.org
      - MAILER_PORT=465
      - MAILER_SECURE=1
      - MAILER_AUTH_USER=youremail@gmail.com
      - MAILER_AUTH_PASSWORD=Y0urP@ssw0rd
      - MAILER_NOREPLY_NAME=Joplin
      - MAILER_NOREPLY_EMAIL=email@email.com

volumes:
  joplindb: