services:
  lubelogger:
    container_name: lubelogger
    hostname: lubelogger
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "8102:8080"  # Map host port 8080 to container port 8080
    volumes:
      - "/opt/data-docker/lubelogger/data:/App/data"  # Persistent storage for SQLite database and uploads
      - "/opt/data-docker/lubelogger/keys:/root/.aspnet/DataProtection-Keys"
      - "/etc/timezone:/etc/timezone:ro"  # Timezone configuration
      - "/etc/localtime:/etc/localtime:ro"  # Local time configuration
    environment:
      TZ: 'America/Toronto'  # Set your timezone
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"

