version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8200:8000"
      - "9200:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/data-docker/portainer:/data"
      - "/opt/data-docker/portainer/ssl-certs:/certs"
    command:
      --sslcert /certs/portainer.crt
      --sslkey /certs/portainer.key
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
      - "docker-volume-backup.stop-during-backup=true"
