services:
  registry:
    image: registry:3
    container_name: docker-registry
    restart: unless-stopped
    ports:
      - "8105:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      OTEL_TRACES_EXPORTER: "none"
      REGISTRY_LOG_LEVEL: info
    volumes:
      - "/opt/data-docker/docker-registry/data:/var/lib/registry"
      - "/opt/data-docker/docker-registry/auth:/auth:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etcp/timezone:ro"
  registry-ui:
    image: ghcr.io/eznix86/docker-registry-ui:latest
    ports:
      - "8106:80"
    environment:
      - REGISTRY_URL=${REGISTRY_REMOTE_URL}
      - REGISTRY_AUTH=${REGISTRY_AUTH_BASE64}

