version: "3.9"
secrets:
  MYSQL_ROOT_PASSWORD:
    file: "/opt/data-etc/pastefy/root_pwd.txt"
  MYSQL_DATABASE:
    file: "/opt/data-etc/pastefy/db.txt"
  MYSQL_USER:
    file: "/opt/data-etc/pastefy/user.txt"
  MYSQL_PASSWORD:
    file: "/opt/data-etc/pastefy/pwd.txt"

services:
  db_pastefy:
    container_name: db_pastefy
    image: "linuxserver/mariadb:10.11.6"
    volumes:
      - "/opt/data-docker/pastefy/mysql:/config"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ="America/Toronto"
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/MYSQL_ROOT_PASSWORD
      - FILE__MYSQL_DATABASE=/run/secrets/MYSQL_DATABASE
      - FILE__MYSQL_USER=/run/secrets/MYSQL_USER
      - FILE__MYSQL_PASSWORD=/run/secrets/MYSQL_PASSWORD
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
  pastefy:
    depends_on:
      - db_pastefy
    image: "interaapps/pastefy:latest"
    container_name: pastefy
    ports:
      - "7810:80"
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: ${PAST_MYSQL_DATABASE}
      DATABASE_USER: ${PAST_MYSQL_USER}
      DATABASE_PASSWORD: ${PAST_MYSQL_PASSWORD}
      DATABASE_HOST: db_pastefy
      DATABASE_PORT: 3306
      AUTH_PROVIDER: NONE
      SERVER_NAME: ${PAST_SERVER_URL}
      PASTEFY_LOGIN_REQUIRED: false
      PASTEFY_LOGIN_REQUIRED_CREATE: true
      PASTEFY_LOGIN_REQUIRED_READ: false
      PASTEFY_ENCRYPTION_DEFAULT: false
      PASTEFY_GRANT_ACCESS_REQUIRED: true
      PASTEFY_PUBLIC_STATS: false
