version: "3.9"

secrets:
  APP_KEY:
    file: /opt/data-etc/firefly/app_key.secret.txt
  MAIL_USERNAME:
    file: /opt/data-etc/firefly/mail_username.secret.txt
  MAIL_PASSWORD:
    file: /opt/data-etc/firefly/mail_password.secret.txt
  DB_USERNAME:
    file: /opt/data-etc/firefly/db_username.secret.txt
  DB_PASSWORD:
    file: /opt/data-etc/firefly/db_password.secret.txt
  DB_HOST:
    file: /opt/data-etc/firefly/db_host.secret.txt
  DB_DATABASE:
    file: /opt/data-etc/firefly/db_database.secret.txt
  MYSQL_ROOT_PASSWORD:
    file: /opt/data-etc/firefly/db_root_password.secret.txt
  MYSQL_USER:
    file: /opt/data-etc/firefly/db_username.secret.txt
  MYSQL_PASSWORD:
    file: /opt/data-etc/firefly/db_password.secret.txt

services:
  firefly-db:
    image: mariadb:latest
    restart: unless-stopped
    container_name: firefly-db
   # ports:
      #- "3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
      MARIADB_ROOT_HOST: firefly-db
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MARIADB_DATABASE: firefly-db
      MARIADB_USER_FILE: /run/secrets/MYSQL_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      TZ: "America/Montreal"
      #PUID: 1000
      #PGID: 1000
    volumes:
      - "/opt/data-docker/volumes/mariadb:/var/lib/mysql"
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass yyccV9QUgbGhPWZ8fjXZnXMN3zT74az4
    volumes:
      - cache:/data
    #ports:
      #- '6379'

  firefly:
    image: fireflyiii/core:latest
    restart: unless-stopped
    container_name: firefly
    depends_on:
      - firefly-db
      - redis
    ports:
      - "7801:8080"
    volumes:
      - "/opt/data-docker/volumes/firefly:/var/www/html/storage/upload"
    environment:
      APP_KEY_FILE: /run/secrets/APP_KEY
      APP_ENV: local
      APP_DEBUG: 'false'
      DEFAULT_LANGUAGE: en_US
      DEFAULT_LOCALE: equal
      SITE_OWNER: admin@firefly.ui24.mywire.com
      TZ: "America/Montreal"
      TRUSTED_PROXIES: "**"
      APP_LOG_LEVEL: notice
      AUDIT_LOG_LEVEL: info
      DB_CONNECTION: mysql
      DB_HOST_FILE: /run/secrets/DB_HOST
      DB_PORT: 3306
      DB_DATABASE_FILE: /run/secrets/DB_DATABASE
      DB_USERNAME_FILE: /run/secrets/MYSQL_USER
      DB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: yyccV9QUgbGhPWZ8fjXZnXMN3zT74az4
      REDIS_SCHEME: tcp
      REDIS_DB: "0"
      REDIS_CACHE_DB: "1"
      MAIL_MAILER: log
      MAIL_HOST: smtp.mailgun.org
      MAIL_PORT: 587
      MAIL_FROM: notreply@firefly.ui24.mywire.com
      MAIL_USERNAME_FILE: /run/secrets/MAIL_USERNAME
      MAIL_PASSWORD_FILE: /run/secrets/MAIL_PASSWORD
      MAIL_ENCRYPTION: tls
      SEND_REGISTRATION_MAIL: 'true'
      SEND_ERROR_MESSAGE: "true"
      SEND_LOGIN_NEW_IP_WARNING: 'true'
      SEND_REPORT_JOURNALS: 'true'
      AUTHENTICATION_GUARD: web
      PUID: 1000
      PGID: 1000
    secrets:
      - APP_KEY
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DB_HOST
      - DB_DATABASE
      - MAIL_USERNAME
      - MAIL_PASSWORD
  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - firefly-db
    environment:
      ADMINER_DEFAULT_SERVER: firefly-db
      MYSQL_ROOT_PASSWORD__FILE: run/secrets/MYSQL_ROOT_PASSWORD
      TZ: "America/Montreal"
    secrets:
      - MYSQL_ROOT_PASSWORD
    restart: unless-stopped
    ports:
      - "7802:8080"

volumes:
  cache:
    driver: local
