services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    volumes:
      - "/opt/data-docker/victoria-metrics:/victoria-metrics-data"
    command:
      - "-retentionPeriod=${VICTORIA_RETENTION_PERIOD}"   # keep it small for homelab
      - "-memory.allowedPercent=40"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "8107:3000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/data-docker/grafana-data:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_ROOT_PWD
      - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource,grafana-assistant-app
