services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=$SECRET_KEY # will use randomUUID() if unset
      - HTTP_ALLOWED=true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/data-docker/convertx/data:/app/data"
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"