version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    ports:
      - "8100:80"
      - "9100:443"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Montreal
    volumes:
      - "/opt/data-docker/volumes/heimdall/config:/config"