version: "3"
services:
  #UI dashboard
  dashboard:
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    ports:
      - 8100:80
      - 8443:443
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=${NETBIRD_MGMT_API_ENDPOINT}
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=${NETBIRD_MGMT_API_ENDPOINT}
      # OIDC
      - AUTH_AUDIENCE=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=
      - AUTH_AUTHORITY=${AUTH_AUTHORITY_URL}
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
      - NETBIRD_TOKEN_SOURCE=accessToken
      # SSL
      - NGINX_SSL_PORT=443
      # Letsencrypt
      - LETSENCRYPT_DOMAIN=
      - LETSENCRYPT_EMAIL=
      - NETBIRD_DISABLE_LETSENCRYPT=true
    volumes:
      - netbird-letsencrypt:/etc/letsencrypt/
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-dashboard.entrypoints=https,http
      - traefik.http.routers.netbird-dashboard.rule=Host(`netbird.jimsgarage.co.uk`)
      - traefik.http.routers.netbird-dashboard.tls=true
      - traefik.http.routers.netbird-dashboard.service=netbird@docker
      - traefik.http.services.netbird.loadbalancer.server.port=80
      - traefik.docker.network=proxy

  # Signal
  signal:
    image: netbirdio/signal:latest
    restart: unless-stopped
    volumes:
      - netbird-signal:/var/lib/netbird
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 10000:80
    #      # port and command for Let's Encrypt validation
    #      - 443:443
    #    command: ["--letsencrypt-domain", "", "--log-file", "console"]
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-signal.entrypoints=https,http
      - traefik.http.routers.netbird-signal.rule=Host(`netbird.jimsgarage.co.uk`) && PathPrefix(`/signalexchange.SignalExchange/`)
      - traefik.http.routers.netbird-signal.tls=true
      - traefik.http.routers.netbird-signal.service=signal@docker
      - traefik.http.services.signal.loadbalancer.server.port=80
      - traefik.http.services.signal.loadbalancer.server.scheme=h2c
      - traefik.docker.network=proxy

  # Management
  management:
    image: netbirdio/management:latest
    restart: unless-stopped
    depends_on:
      - dashboard
    volumes:
      - netbird-mgmt:/var/lib/netbird
      - netbird-letsencrypt:/etc/letsencrypt:ro
      - /opt/data-docker/netbird/config/management.json:/etc/netbird/management.json
    ports:
      - 9443:443 #API port
    #    # command for Let's Encrypt validation without dashboard container
    #    command: ["--letsencrypt-domain", "", "--log-file", "console"]
    command: [
      "--port", "443",
      "--log-file", "console",
      "--log-level", "debug"
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.jimsgarage.co.uk",
      "--dns-domain=jimsgarage.co.uk"
    ]
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-api.entrypoints=https,http
      - traefik.http.routers.netbird-api.rule=Host(`netbird.jimsgarage.co.uk`) && PathPrefix(`/api`)
      - traefik.http.routers.netbird-api.tls=true
      - traefik.http.routers.netbird-api.service=api
      - traefik.http.services.api.loadbalancer.server.port=443

      - traefik.http.routers.netbird-management.entrypoints=https,http
      - traefik.http.routers.netbird-management.rule=Host(`netbird.jimsgarage.co.uk`) && PathPrefix(`/management.ManagementService/`)
      - traefik.http.routers.netbird-management.tls=true
      - traefik.http.routers.netbird-management.service=netbird-management
      - traefik.http.services.netbird-management.loadbalancer.server.port=443
      - traefik.http.services.netbird-management.loadbalancer.server.scheme=h2c

      - traefik.docker.network=proxy

  # Coturn
  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    domainname: netbird.jimsgarage.co.uk
    volumes:
      - /opt/data-docker/netbird/config/turnserver.conf:/etc/turnserver.conf:ro
    #      - ./privkey.pem:/etc/coturn/private/privkey.pem:ro
    #      - ./cert.pem:/etc/coturn/certs/cert.pem:ro
    network_mode: host
    environment:
      - TURN_PORT=3478
      - TURN_EXTERNAL_IP=${HOST_IP}
    command:
      - -c /etc/turnserver.conf

volumes:
  netbird-mgmt:
  netbird-signal:
  netbird-letsencrypt:

networks:
  proxy:
