version: "3.9"

secrets:
  POSTGRES_DB:
    file: /opt/data-etc/focalboard/db.secret.txt
  POSTGRES_USER:
    file: /opt/data-etc/focalboard/db_user.secret.txt
  POSTGRES_PASSWORD:
    file: /opt/data-etc/focalboard/db_pwd.secret.txt

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    ports:
      - "7803:8000"
      - "7902:9092"
    depends_on:
      - focalboard-db
    restart: unless-stopped
    volumes:
      - "/opt/data-docker/focalboard/data:/data"
      - "/opt/data-docker/focalboard/data-opt/config.json:/opt/focalboard/config.json"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      TZ: "America/Toronto"
    networks:
      - focal-net
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    security_opt:
      - no-new-privileges:true

  focalboard-db:
    image: postgres:16.2
    container_name: focalboard-db
    restart: unless-stopped
    volumes:
      - "/opt/data-docker/focalboard/postgresql:/var/lib/postgresql/data"
      - "/opt/data-docker/focalboard/db-backups:/var/lib/postgresql/focal-backups/"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB  #boards
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER #boardsuser
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD #boardsuser-password
      TZ: "America/Toronto"
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - focal-net
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
      - docker-volume-backup.archive-pre=/bin/bash -c 'pg_dump -U $(< /run/secrets/POSTGRES_USER) $(< /run/secrets/POSTGRES_DB) > /var/lib/postgresql/focal-backups/bck_db_focal$(date +%Y%m%d-%H%M).sql'
  adminer_focal:
    image: adminer:latest
    container_name: adminer_focal
    depends_on:
      - focalboard-db
    security_opt:
      - no-new-privileges:true
    environment:
      ADMINER_DEFAULT_SERVER: focalboard-db
    networks:
      - focal-net
    restart: unless-stopped
    ports:
      - "7804:8080"

networks:
  focal-net:
