version: "3.9"
secrets:
  DB_ROOT_PWD:
    file: /opt/data-etc/vikunja/db_root_pwd.secret.txt
  MYSQL_PWD:
    file: /opt/data-etc/vikunja/db_pwd.secret.txt
  CONFIG_SQLPWD:
    file: /opt/data-etc/vikunja/mysql.sqlpwd
services:
  vikunja:
    image: "vikunja/vikunja"
    container_name: "vikunja"
    ports:
      - "7802:3456"
    volumes:
      - "/opt/data-docker/vikunja/files:/app/vikunja/files"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
  db:
    image: "mariadb:11"
    container_name: "vikunja_db"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    secrets:
      - MYSQL_PWD
      - DB_ROOT_PWD
      - CONFIG_SQLPWD
    environment:
      MYSQL_ROOT_PASSWORD__FILE: run/secrets/DB_ROOT_PWD
      MYSQL_USER: "${VIKUNJA_USER}"
      MYSQL_PASSWORD__FILE: run/secrets/MYSQL_PWD
      MYSQL_DATABASE: "${VIKUNJA_DB}"
    security_opt:
      - no-new-privileges:true
    volumes:
      - "/opt/data-docker/vikunja/mysql:/var/lib/mysql"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"

  redis:
    image: "redis:alpine"
    container_name: "vikunja_redis"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${VK_REDIS_PASSWORD}
    volumes:
      - "cache:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - '6379'
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"

volumes:
  cache:
    driver: local