version: "3.9"

secrets:
  POSTGRES_PWD:
    file: /opt/data-etc/gitea/db_pwd.secret.txt
  POSTGRES_USER:
    file: /opt/data-etc/gitea/db_user.secret.txt
  POSTGRES_DB:
    file: /opt/data-etc/gitea/db_name.secret.txt

networks:
  gitea:
    external: false

services:
  db:
    image: postgres:14
    container_name: db-gitea
    restart: unless-stopped
    environment:
      POSTGRES_USER__FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD__FILE: /run/secrets/POSTGRES_PWD
      POSTGRES_DB__FILE: /run/secrets/POSTGRES_DB
      TZ: "${TIME_ZONE}"
    secrets:
      - POSTGRES_PWD
      - POSTGRES_USER
      - POSTGRES_DB
    networks:
      - gitea
    volumes:
      - "/opt/data-adm-docker/volumes/gitea/postgres:/var/lib/postgresql/data"

  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - /opt/data-etc/gitea/config.env
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db-gitea:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    networks:
      - gitea
    volumes:
      - "/opt/data-adm-docker/volumes/gitea/gitea-data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/git/.ssh/:/data/git/.ssh"
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"