services:
  headscale:
    image: headscale/headscale:0.26.1
    container_name: headscale
    restart: unless-stopped
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    command: serve
    ports:
      - "41641:41641/udp" # WireGuard
      - "8080:8080/tcp"
    networks:
      - proxy
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:2025.07.12
    container_name: headscale-ui
    restart: unless-stopped
    ports:
      - "8081:8080/tcp"
    networks:
      - proxy
  headscale-admin:
    image: goodieshq/headscale-admin:0.25.6
    container_name: headscale-admin
    restart: unless-stopped
    ports:
      - "8082:80/tcp"
    networks:
      - proxy
networks:
  proxy:
    external: true