name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_server
    ports:
      - '${PORT:-3010}:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - /opt/data-docker/affine/app/storage:/root/.affine/storage
      - /opt/data-docker/affine/app/config:/root/.affine/config
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /opt/data-etc/affine/config.env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${AFFINE_DB_USERNAME}:${AFFINE_DB_PASSWORD}@postgres:5432/${AFFINE_DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
      - selfhosted=true
      - OPENAI_API_KEY=ollama
      - OPENAI_BASE_URL=http://192.168.20.31:11434/v1
      - AFFINE_SERVER_ALLOWED_ORIGINS=*
      - AFFINE_SERVER_EXTERNAL_URL=${AFFINE_SERVER_EXTERNAL_URL}
      - AFFINE_SERVER_HOST=${AFFINE_SERVER_HOST}
      - AFFINE_SERVER_HTTPS=true
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - /opt/data-docker/affine/app/storage:/root/.affine/storage
      - /opt/data-docker/affine/app/config:/root/.affine/config
      - /etc/localtime:/etc/localtime:ro
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - /opt/data-etc/affine/config.env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${AFFINE_DB_USERNAME}:${AFFINE_DB_PASSWORD}@postgres:5432/${AFFINE_DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    env_file:
      - /opt/data-etc/affine/config.env
    volumes:
      - /opt/data-docker/affine/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${AFFINE_DB_USERNAME}
      POSTGRES_PASSWORD: ${AFFINE_DB_PASSWORD}
      POSTGRES_DB: ${AFFINE_DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${AFFINE_DB_USERNAME}", '-d', "${AFFINE_DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  affine-copilot-fix:
    container_name: affine-copilot-fix
    user: "1000:1000"
    build:
      context: ./affine-copilot-fix-main
      dockerfile: Dockerfile
    volumes:
      - /opt/data-docker/affine/logs:/app/src/logs
    environment:
      - CREATE_LOG=True
      - OPENAI_API_KEY=ollama
      - OPENAI_BASE_URL=http://192.168.20.31:11434/v1/
      - OPENAI_MODEL=gemini-2.5-flash:latest  # Or any openrouter model
    ports:
      - 5000:5000
    image: affine-copilot-fix:latest
    networks:
      - affine-net
