version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=America/Montreal
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_LOG_LEVEL=warn
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCOPE=toUpdateScope
      #- WATCHTOWER_NOTIFICATIONS=email
      #- WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower-mail@sp1.theworkpc.com
      #- WATCHTOWER_NOTIFICATION_EMAIL_TO=sp1-WATCHTOWER_5DDjIsU@sp1.theworkpc.com
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=192.168.20.7
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=1025
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
