name: mailcatcher
services:
  mailcatcher:
    restart: always
    image: "dockage/mailcatcher"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/data-docker/mailcatcher/logs:/var/mailcatcher/logs"
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    ports:
      - "1080:1080"
      - "1025:1025"