services:
  excalidraw:
    image: "excalidraw/excalidraw:latest"
    container_name: excalidraw
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "8101:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"