version: '3'

services:
  docuseal:
    container_name: docuseal
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - /opt/data-docker/docuseal:/data
    environment:
      #- FORCE_SSL=${HOST}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      #- HOST=
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_ADDRESS=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTHENTICATION=login
      - SMTP_FROM=${SMTP_USERNAME}

  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - '/opt/data-docker/postgres-docuseal:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
