services:
  management:
    image: netbirdio/management:latest
    restart: unless-stopped
    container_name: netbird-management
    command: ["--log-level", "debug"]
    volumes:
      - /opt/data-docker/netbird/management:/var/lib/netbird
      - /opt/data-docker/netbird/config/management.json:/etc/netbird/management.json
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    environment:
      - NETBIRD_MGMT_API_ENDPOINT=${NETBIRD_MGMT_API_ENDPOINT}
      - LOG_LEVEL=debug
      - NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT=${NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT}
      - NETBIRD_AUTH_AUDIENCE=${AUTH_CLIENT_ID}
      - NETBIRD_AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - NETBIRD_AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - NETBIRD_USE_AUTH0=false
      - NETBIRD_MGMT_IDP=authentik
      - NETBIRD_IDP_MGMT_CLIENT_ID=${AUTH_CLIENT_ID}
      - NETBIRD_IDP_MGMT_EXTRA_USERNAME=${NETBIRD_IDP_MGMT_EXTRA_USERNAME}
      - NETBIRD_IDP_MGMT_EXTRA_PASSWORD=${NETBIRD_IDP_MGMT_EXTRA_PASSWORD}
      - NETBIRD_AUTH_DEVICE_AUTH_PROVIDER=hosted
      - NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE=${AUTH_CLIENT_ID}
      - NETBIRD_TOKEN_SOURCE=accessToken
      - NETBIRD_DISABLE_LETSENCRYPT=true
      - NETBIRD_AUTH_PKCE_DISABLE_PROMPT_LOGIN=true
    ports:
      - "33073:33073"
    networks:
      - netbird

  dashboard:
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    container_name: netbird-dashboard
    environment:
      - NETBIRD_MGMT_API_ENDPOINT=${NETBIRD_MGMT_API_ENDPOINT}
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=${NETBIRD_MGMT_API_ENDPOINT}
      - AUTH_AUDIENCE=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_AUTHORITY=${AUTH_AUTHORITY_URL}
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - NETBIRD_TOKEN_SOURCE=accessToken
      - NGINX_SSL_PORT=443
      - NETBIRD_DISABLE_LETSENCRYPT=true
      - NETBIRD_AUTH_PKCE_DISABLE_PROMPT_LOGIN=true
      - LOG_LEVEL=debug
    ports:
      - "8100:80"
    networks:
      - netbird
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  signal:
    image: netbirdio/signal:latest
    restart: unless-stopped
    container_name: netbird-signal
    environment:
      - LOG_LEVEL=debug
    ports:
      - "10000:10000"
    networks:
      - netbird
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    container_name: netbird-coturn
    command: -c /etc/turnserver.conf
    volumes:
      - /opt/data-docker/netbird/config/turnserver.conf:/etc/turnserver.conf
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    network_mode: host
    environment:
      - TURN_PORT=3478
      - TURN_EXTERNAL_IP=${HOST_IP}
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"


networks:
  netbird:
    driver: bridge