services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "8102:4533"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    networks:
      - media-net
    environment:
      TZ: America/Montreal
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 6h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/opt/data-docker/media_stream/navidrome:/data"
      - "/nfs/stream_data/audios:/music:ro" #optional

networks:
  media-net:
    external: true