version: '3.9'
services:
  webdav:
    image: bytemark/webdav
    container_name: music-webdav
    restart: unless-stopped
    ports:
      - "8101:80"
    environment:
      - AUTH_TYPE=Digest
      - USERNAME=test
      - PASSWORD=test
    volumes:
      #- "/opt/data-docker/media_stream/webdav/data:/var/lib/dav"
      - "/nfs/stream_data/music:/var/lib/dav"
      #- "/opt/data-docker/media_stream/webdav/etc/user.passwd:/user.passwd:ro"
