version: "3.9"
name: webdav

secrets:
  USERNAME_SC:
    file: /opt/data-docker/media_stream/webdav-music/username.secret.txt
  PASSWORD_SC:
    file: /opt/data-docker/media_stream/webdav-music/password.secret.txt
services:
  docker-nginx-webdav:
    image: maltokyo/docker-nginx-webdav
    container_name: music-webdav
    restart: unless-stopped
    entrypoint: [ '/bin/bash', '-c', 'export USERNAME=$$(cat /run/secrets/USERNAME_SC); export PASSWORD=$$(cat /run/secrets/PASSWORD_SC); /entrypoint.sh && nginx -g "daemon off;"' ]
    security_opt:
      - no-new-privileges:true
    ports:
      - "8101:80"
    volumes:
      - "/nfs/stream_data/audios:/media/data:ro"
    secrets:
      - USERNAME_SC
      - PASSWORD_SC
    environment:
      - TZ=America/Toronto
      - USERNAME_FILE=/run/secrets/USERNAME_SC
      - PASSWORD_FILE=/run/secrets/PASSWORD_SC
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
