version: '3.9'
services:
  webdav:
    image: loganmarchione/docker-webdav-nginx:latest
    container_name: music-webdav
    restart: unless-stopped
    ports:
      - "8101:80"
    environment:
      - WEBDAV_USER=user
      - WEBDAV_PASS=password1
      - NGINX_CLIENT_MAX_BODY_SIZE=500M
    volumes:
      - "/opt/data-docker/media_stream/webdav/lib:/var/www/webdav"
      - "/nfs/stream_data/music:/var/www/webdav/music:ro"
      #- "/nfs/stream_data/music:/var/lib/dav"
      #- "/opt/data-docker/media_stream/webdav/etc/user.passwd:/user.passwd:ro"
