services:
  redis:
    container_name: searxng-redis
    image: "docker.io/valkey/valkey:8-alpine"
    command: redis-server --save "" --appendonly "no"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8201:8080"
    volumes:
      - "/opt/data-docker/searxng/data:/etc/searxng"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - TZ=America/Toronto
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
      - "docker-volume-backup.stop-during-backup=true"
networks:
  searxng:
    ipam:
      driver: default

