version: '3.9'

secrets:
  SMTP_USERNAME:
    file: /opt/data-etc/vaultwarden/smtp_user.secret.txt
  SMTP_PASSWORD:
    file: /opt/data-etc/vaultwarden/smtp_pwd.secret.txt
  ADMIN_TOKEN_ARGON:
    file: /opt/data-etc/vaultwarden/admin_token_argon.secret.txt

services:
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: vaultwarden/server:latest
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - "/opt/data-docker/password_manager:/data"
    ports:
      - "8100:80"
    environment:
      SMTP_HOST: ${PWD_SMTP_HOST}
      SMTP_FROM: ${PWD_SMTP_FROM}
      SMTP_FROM_NAME: Password Vault
      SMTP_SECURITY: starttls
      SMTP_PORT: ${PWD_SMTP_PORT}
      SMTP_USERNAME_FILE: /run/secrets/SMTP_USERNAME
      SMTP_PASSWORD_FILE: /run/secrets/SMTP_PASSWORD
      SMTP_TIMEOUT: 30
      SMTP_AUTH_MECHANISM: "TLS"
      LOGIN_RATELIMIT_MAX_BURST: 10
      LOGIN_RATELIMIT_SECONDS: 60
      DOMAIN: ${PWD_DOMAIN} #change this to your URL
      INVITATION_ORG_NAME: HomePwd-Mg #change this to your company name
      INVITATIONS_ALLOWED: false
      ADMIN_TOKEN_FILE: /run/secrets/ADMIN_TOKEN_ARGON #generate your own admin token
      SIGNUPS_ALLOWED: true
      SIGNUPS_VERIFY: true
      SIGNUPS_VERIFY_RESEND_TIME: 3600
      SIGNUPS_VERIFY_RESEND_LIMIT: 6
      EMERGENCY_ACCESS_ALLOWED: true
      SENDS_ALLOWED: true
      WEB_VAULT_ENABLED: true
    secrets:
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - ADMIN_TOKEN_ARGON
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"