- name: install latest iftop on all hosts
  hosts: "*"
  tasks:
    - name: install iftop
      apt:
        name: iftop
        state: present
        update_cache: true
      become: true
    - name: install htop
      apt:
        name: htop
        state: present
        update_cache: true
      become: true