version: "3.9"
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:latest
    container_name: orbital-sync
    depends_on:
      pihole:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
    env_file:
      - /opt/data-docker-etc/pihole/orbital-sync.env
    environment:
      TZ: America/Montreal
    networks:
      pihole_local_network:
        ipv4_address: 172.20.0.4
networks:
  pihole_local_network:
    external: true

