dns_transport_list:
  - GETDNS_TRANSPORT_TLS
dnssec: GETDNS_EXTENSION_TRUE
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 256
dnssec_return_status: GETDNS_EXTENSION_TRUE
tls_min_version: GETDNS_TLS1_3
edns_client_subnet_private : 1
idle_timeout: 10000
listen_addresses:
  - 0.0.0.0
  - 0:0:0:0:0:0:0:0
# The following information can be found at my.nextdns.io/xxxxxx/setup and then scroll down to "Stubby" and copy/paste from there to here.
round_robin_upstreams: 1
upstream_recursive_servers:
  - address_data: 45.90.28.0
    tls_auth_name: "xxxxxx.dns.nextdns.io"
  - address_data: 2a07:a8c0::0
    tls_auth_name: "xxxxxx.dns.nextdns.io"
  - address_data: 45.90.30.0
    tls_auth_name: "xxxxxx.dns.nextdns.io"
  - address_data: 2a07:a8c1::0
    tls_auth_name: "xxxxxx.dns.nextdns.io"
