version: "3.9"
services:
  portainer-agent:
    container_name: portainer-agent
    deploy:
      mode: global
    image: portainer/agent:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-agent_default
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
networks:
  portainer-agent_default:
