# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "ultrasecretkey"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
search:
  autocomplete: "duckduckgo"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
general:
  instance_name: "My-Search"
  debug: true
  enable_metrics: true
  contact_url: false

