services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
      - "docker-volume-backup.stop-during-backup=true"
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
    volumes:
      - "/opt/data-docker/duplicati/config:/config"
      - "${PBS_DISK_PATH}:/pbs_data"
      - "${ZFSA_ABZ_DOC_PATH}:/zfsa_documents"
      - "/opt/rclone/1.70.3:/opt/rclone"
    ports:
      - "8101:8200"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true