timezone: "America/Montreal"

package_update: true
package_upgrade: true
packages:
  - git
  - htop

# The top level settings are used as module
# and base configuration.
# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
  - name: athena
    lock_passwd: False
    passwd: $6$7Y/GenEpggFTX0k$ywMQDFt2sVXyvaFi5f4ROJXKnodeFwf9KFwfDjCjpcgTEt8rELeyNzy.KbYEDqbCgMGsTdjWWGa3eopRO9Opf/
    gecos: Athena
    groups: [ athena ]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMc9HCPSkZPTKJrGXa1bn/o1kMHOZQtm62TjBZ78hSjV bobdi@pve02
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB01BZ9pKo4LP+qg0ys8b5nEokM8eYtxqHzBiORW3K5c sabadam@pop-os
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJjv918T58A/Y5x1Jh7QyFU1RHAlnSKYqPAVfyH1T27H bobdi@mail.com
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDnCA+0/upEyMGFWGweNibmsbtOmkA7E3XH4CYZsNtPj pod3-800
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGzUYSFlpn4y8sCLVAnw3iHEMTI1hjb3qpOx2e92Q3Ql macbook-mi2012@yopmail.com
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILLPSiBVls0oTzqv15u/yZRmLeYsrHAh9stlhTG/3V7Y bobdi@zorin.os
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKafuX8+w6Gej7XYQ77P0U5Th8+ptoTrZ19ujtQGx2gM dell7415@yopmail.com
  - name: artemis
    lock_passwd: False
    passwd: $6$yxNkzoJEO5gnoGH$K6Xq7A4YxqmGqBhZXm6q/6wWvqQzKpByQ62yEXS.eMjPrfOKPRIlpEs3BYWtDQpVgofdZRm/Lt0kglHLW/e3u.
    gecos: Artemis root
    groups: [ adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: true


# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# If you use datasource_list array, keep array items in a single line.
# If you use multi line array, ds-identify script won't read array items.
# Example datasource config
# datasource:
#    Ec2:
#      metadata_urls: [ 'blah.com' ]
#      timeout: 5 # (defaults to 50 seconds)
#      max_wait: 10 # (defaults to 120 seconds)




# The modules that run in the 'init' stage
cloud_init_modules:
  - migrator
  - seed_random
  - bootcmd
  - write-files
  - growpart
  - resizefs
  - disk_setup
  - mounts
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - ca-certs
  - rsyslog
  - users-groups
  - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
  - wireguard
  - snap
  - ubuntu_autoinstall
  - ssh-import-id
  - keyboard
  - locale
  - set-passwords
  - grub-dpkg
  - apt-pipelining
  - apt-configure
  - ubuntu-advantage
  - ntp
  - timezone
  - disable-ec2-metadata
  - runcmd
  - byobu

# The modules that run in the 'final' stage
cloud_final_modules:
  - package-update-upgrade-install
  - fan
  - landscape
  - lxd
  - ubuntu-drivers
  - write-files-deferred
  - puppet
  - chef
  - ansible
  - mcollective
  - salt-minion
  - reset_rmc
  - rightscale_userdata
  - scripts-vendor
  - scripts-per-once
  - scripts-per-boot
  - scripts-per-instance
  - scripts-user
  - ssh-authkey-fingerprints
  - keys-to-console
  - install-hotplug
  - phone-home
  - final-message
  - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
  # This will affect which distro class gets used
  distro: ubuntu
  # Default user name + that default users groups (if added/used)
  #default_user:
  #  name: artemis
  #  lock_passwd: True
  #  gecos: Artemis root
  #  groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
  #  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
  #  shell: /bin/bash
  network:
    renderers: ['netplan', 'eni', 'sysconfig']
    activators: ['netplan', 'eni', 'network-manager', 'networkd']
  # Automatically discover the best ntp_client
  ntp_client: auto
  # Other config here will be given to the distro class and/or path classes
  paths:
    cloud_dir: /var/lib/cloud/
    templates_dir: /etc/cloud/templates/
  package_mirrors:
    - arches: [i386, amd64]
      failsafe:
        primary: http://archive.ubuntu.com/ubuntu
        security: http://security.ubuntu.com/ubuntu
      search:
        primary:
          - http://%(ec2_region)s.ec2.archive.ubuntu.com/ubuntu/
          - http://%(availability_zone)s.clouds.archive.ubuntu.com/ubuntu/
          - http://%(region)s.clouds.archive.ubuntu.com/ubuntu/
        security: []
    - arches: [arm64, armel, armhf]
      failsafe:
        primary: http://ports.ubuntu.com/ubuntu-ports
        security: http://ports.ubuntu.com/ubuntu-ports
      search:
        primary:
          - http://%(ec2_region)s.ec2.ports.ubuntu.com/ubuntu-ports/
          - http://%(availability_zone)s.clouds.ports.ubuntu.com/ubuntu-ports/
          - http://%(region)s.clouds.ports.ubuntu.com/ubuntu-ports/
        security: []
    - arches: [default]
      failsafe:
        primary: http://ports.ubuntu.com/ubuntu-ports
        security: http://ports.ubuntu.com/ubuntu-ports
  ssh_svcname: ssh