version: '3.9'
services:
  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    restart: always
    env_file:
      - $HOME/.offen/offen.backup.env
    security_opt:
      - no-new-privileges:true
    environment:
      WEBDAV_URL: ${OFS_WEBDAV_DEST_HOST}
      WEBDAV_PATH: ${OFS_BACKUP_DEST}
      WEBDAV_USERNAME: ${OFS_WEBDAV_USERNAME}
      WEBDAV_PASSWORD: ${OFS_WEBDAV_PASSWORD}
      WEBDAV_URL_INSECURE: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.offen/offen-config:/etc/dockervolumebackup/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${OFS_BACKUP_SRC_APPS_FOLDER}:/backup/apps:ro
      - ${OFS_BACKUP_SRC_ETC_FOLDER}:/backup/etc:ro
      - ${OFS_BACKUP_DEST}:/archive

    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"

