version: '3.9'
secrets:
  USERNAME_WEBDAV:
    file: $HOME/.offen/username-dav.secret.txt
  PASSWORD_WEBDAV:
    file: $HOME/.offen/password-dav.secret.txt
services:
  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    entrypoint: [ '/bin/bash', '-c', 'export WEBDAV_USERNAME=$$(cat /run/secrets/USERNAME_WEBDAV); export WEBDAV_PASSWORD=$$(cat /run/secrets/PASSWORD_WEBDAV); /root/entrypoint.sh;"' ]
    restart: always
    env_file:
      - $HOME/.offen/offen.backup.env
    security_opt:
      - no-new-privileges:true
    environment:
      WEBDAV_URL: ${OFS_WEBDAV_DEST_HOST}
      WEBDAV_PATH: ${OFS_BACKUP_DEST}
      WEBDAV_USERNAME_FILE: /run/secrets/USERNAME_WEBDAV
      WEBDAV_PASSWORD_FILE: /run/secrets/PASSWORD_WEBDAV
      WEBDAV_URL_INSECURE: true
    secrets:
      - USERNAME_WEBDAV
      - PASSWORD_WEBDAV
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.offen/offen-config:/etc/dockervolumebackup/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${OFS_BACKUP_SRC_APPS_FOLDER}:/backup/apps:ro
      - ${OFS_BACKUP_SRC_ETC_FOLDER}:/backup/etc:ro
      - ${OFS_BACKUP_DEST}:/archive

    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"

