version: '3.9'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin-share
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "7805:3000"
    volumes:
      - "/opt/data-docker/pingvin-share/data:/opt/app/backend/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"