services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    ports:
      - "8100:80"
      - "9100:443"
    security_opt:
      - no-new-privileges:true
    volumes:
      - "/opt/data-docker/heimdall/config:/config"
    labels:
      - "com.centurylinklabs.watchtower.scope=toUpdateScope"
      - "docker-volume-backup.stop-during-backup=true"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"