version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    #environment:
    #  - PUID=1000
    #  - PGID=
    volumes:
      - "/opt/data-docker/homeassistant/apps:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      #- /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
