version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      #- PUID=
      #- PGID=
      - TZ=America/Toronto
    volumes:
      - /home/bobdi/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      #- /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
